name: test

# ğŸ” DÃ©clenchement du workflow Ã  chaque push sur la branche main
on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest  # Le job tourne sur une machine virtuelle Ubuntu

    steps:
      # Ã‰tape 1 â€” RÃ©cupÃ¨re ton code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ã‰tape 2 â€” ExÃ©cute un simple script
      - name: Say Hello World
        run: docker compose up -d
